// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema } from "@latticexyz/store/src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "@latticexyz/store/src/EncodedLengths.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

struct ConvertRatioData {
  uint8 num;
  uint8 denom;
}

library ConvertRatio {
  // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "", name: "ConvertRatio", typeId: RESOURCE_TABLE });`
  ResourceId constant _tableId = ResourceId.wrap(0x74620000000000000000000000000000436f6e76657274526174696f00000000);

  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x0002020001010000000000000000000000000000000000000000000000000000);

  // Hex-encoded key schema of (bytes16, bytes16)
  Schema constant _keySchema = Schema.wrap(0x002002004f4f0000000000000000000000000000000000000000000000000000);
  // Hex-encoded value schema of (uint8, uint8)
  Schema constant _valueSchema = Schema.wrap(0x0002020000000000000000000000000000000000000000000000000000000000);

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](2);
    keyNames[0] = "fromType";
    keyNames[1] = "toType";
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](2);
    fieldNames[0] = "num";
    fieldNames[1] = "denom";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get num.
   */
  function getNum(bytes16 fromType, bytes16 toType) internal view returns (uint8 num) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(fromType);
    _keyTuple[1] = bytes32(toType);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint8(bytes1(_blob)));
  }

  /**
   * @notice Get num.
   */
  function _getNum(bytes16 fromType, bytes16 toType) internal view returns (uint8 num) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(fromType);
    _keyTuple[1] = bytes32(toType);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint8(bytes1(_blob)));
  }

  /**
   * @notice Set num.
   */
  function setNum(bytes16 fromType, bytes16 toType, uint8 num) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(fromType);
    _keyTuple[1] = bytes32(toType);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((num)), _fieldLayout);
  }

  /**
   * @notice Set num.
   */
  function _setNum(bytes16 fromType, bytes16 toType, uint8 num) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(fromType);
    _keyTuple[1] = bytes32(toType);

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((num)), _fieldLayout);
  }

  /**
   * @notice Get denom.
   */
  function getDenom(bytes16 fromType, bytes16 toType) internal view returns (uint8 denom) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(fromType);
    _keyTuple[1] = bytes32(toType);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (uint8(bytes1(_blob)));
  }

  /**
   * @notice Get denom.
   */
  function _getDenom(bytes16 fromType, bytes16 toType) internal view returns (uint8 denom) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(fromType);
    _keyTuple[1] = bytes32(toType);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (uint8(bytes1(_blob)));
  }

  /**
   * @notice Set denom.
   */
  function setDenom(bytes16 fromType, bytes16 toType, uint8 denom) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(fromType);
    _keyTuple[1] = bytes32(toType);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((denom)), _fieldLayout);
  }

  /**
   * @notice Set denom.
   */
  function _setDenom(bytes16 fromType, bytes16 toType, uint8 denom) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(fromType);
    _keyTuple[1] = bytes32(toType);

    StoreCore.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((denom)), _fieldLayout);
  }

  /**
   * @notice Get the full data.
   */
  function get(bytes16 fromType, bytes16 toType) internal view returns (ConvertRatioData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(fromType);
    _keyTuple[1] = bytes32(toType);

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreSwitch.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Get the full data.
   */
  function _get(bytes16 fromType, bytes16 toType) internal view returns (ConvertRatioData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(fromType);
    _keyTuple[1] = bytes32(toType);

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreCore.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function set(bytes16 fromType, bytes16 toType, uint8 num, uint8 denom) internal {
    bytes memory _staticData = encodeStatic(num, denom);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(fromType);
    _keyTuple[1] = bytes32(toType);

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function _set(bytes16 fromType, bytes16 toType, uint8 num, uint8 denom) internal {
    bytes memory _staticData = encodeStatic(num, denom);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(fromType);
    _keyTuple[1] = bytes32(toType);

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function set(bytes16 fromType, bytes16 toType, ConvertRatioData memory _table) internal {
    bytes memory _staticData = encodeStatic(_table.num, _table.denom);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(fromType);
    _keyTuple[1] = bytes32(toType);

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function _set(bytes16 fromType, bytes16 toType, ConvertRatioData memory _table) internal {
    bytes memory _staticData = encodeStatic(_table.num, _table.denom);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(fromType);
    _keyTuple[1] = bytes32(toType);

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Decode the tightly packed blob of static data using this table's field layout.
   */
  function decodeStatic(bytes memory _blob) internal pure returns (uint8 num, uint8 denom) {
    num = (uint8(Bytes.getBytes1(_blob, 0)));

    denom = (uint8(Bytes.getBytes1(_blob, 1)));
  }

  /**
   * @notice Decode the tightly packed blobs using this table's field layout.
   * @param _staticData Tightly packed static fields.
   *
   *
   */
  function decode(
    bytes memory _staticData,
    EncodedLengths,
    bytes memory
  ) internal pure returns (ConvertRatioData memory _table) {
    (_table.num, _table.denom) = decodeStatic(_staticData);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord(bytes16 fromType, bytes16 toType) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(fromType);
    _keyTuple[1] = bytes32(toType);

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord(bytes16 fromType, bytes16 toType) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(fromType);
    _keyTuple[1] = bytes32(toType);

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(uint8 num, uint8 denom) internal pure returns (bytes memory) {
    return abi.encodePacked(num, denom);
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(uint8 num, uint8 denom) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory _staticData = encodeStatic(num, denom);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple(bytes16 fromType, bytes16 toType) internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(fromType);
    _keyTuple[1] = bytes32(toType);

    return _keyTuple;
  }
}
