// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema } from "@latticexyz/store/src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "@latticexyz/store/src/EncodedLengths.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

struct SwapRatioData {
  bytes32 hostCopy;
  uint16 num;
  uint16 denom;
}

library SwapRatio {
  // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "", name: "SwapRatio", typeId: RESOURCE_TABLE });`
  ResourceId constant _tableId = ResourceId.wrap(0x7462000000000000000000000000000053776170526174696f00000000000000);

  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x0024030020020200000000000000000000000000000000000000000000000000);

  // Hex-encoded key schema of (bytes16, bytes16, bytes32)
  Schema constant _keySchema = Schema.wrap(0x004003004f4f5f00000000000000000000000000000000000000000000000000);
  // Hex-encoded value schema of (bytes32, uint16, uint16)
  Schema constant _valueSchema = Schema.wrap(0x002403005f010100000000000000000000000000000000000000000000000000);

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](3);
    keyNames[0] = "fromType";
    keyNames[1] = "toType";
    keyNames[2] = "host";
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](3);
    fieldNames[0] = "hostCopy";
    fieldNames[1] = "num";
    fieldNames[2] = "denom";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get hostCopy.
   */
  function getHostCopy(bytes16 fromType, bytes16 toType, bytes32 host) internal view returns (bytes32 hostCopy) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(fromType);
    _keyTuple[1] = bytes32(toType);
    _keyTuple[2] = host;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (bytes32(_blob));
  }

  /**
   * @notice Get hostCopy.
   */
  function _getHostCopy(bytes16 fromType, bytes16 toType, bytes32 host) internal view returns (bytes32 hostCopy) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(fromType);
    _keyTuple[1] = bytes32(toType);
    _keyTuple[2] = host;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (bytes32(_blob));
  }

  /**
   * @notice Set hostCopy.
   */
  function setHostCopy(bytes16 fromType, bytes16 toType, bytes32 host, bytes32 hostCopy) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(fromType);
    _keyTuple[1] = bytes32(toType);
    _keyTuple[2] = host;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((hostCopy)), _fieldLayout);
  }

  /**
   * @notice Set hostCopy.
   */
  function _setHostCopy(bytes16 fromType, bytes16 toType, bytes32 host, bytes32 hostCopy) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(fromType);
    _keyTuple[1] = bytes32(toType);
    _keyTuple[2] = host;

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((hostCopy)), _fieldLayout);
  }

  /**
   * @notice Get num.
   */
  function getNum(bytes16 fromType, bytes16 toType, bytes32 host) internal view returns (uint16 num) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(fromType);
    _keyTuple[1] = bytes32(toType);
    _keyTuple[2] = host;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (uint16(bytes2(_blob)));
  }

  /**
   * @notice Get num.
   */
  function _getNum(bytes16 fromType, bytes16 toType, bytes32 host) internal view returns (uint16 num) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(fromType);
    _keyTuple[1] = bytes32(toType);
    _keyTuple[2] = host;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (uint16(bytes2(_blob)));
  }

  /**
   * @notice Set num.
   */
  function setNum(bytes16 fromType, bytes16 toType, bytes32 host, uint16 num) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(fromType);
    _keyTuple[1] = bytes32(toType);
    _keyTuple[2] = host;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((num)), _fieldLayout);
  }

  /**
   * @notice Set num.
   */
  function _setNum(bytes16 fromType, bytes16 toType, bytes32 host, uint16 num) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(fromType);
    _keyTuple[1] = bytes32(toType);
    _keyTuple[2] = host;

    StoreCore.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((num)), _fieldLayout);
  }

  /**
   * @notice Get denom.
   */
  function getDenom(bytes16 fromType, bytes16 toType, bytes32 host) internal view returns (uint16 denom) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(fromType);
    _keyTuple[1] = bytes32(toType);
    _keyTuple[2] = host;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (uint16(bytes2(_blob)));
  }

  /**
   * @notice Get denom.
   */
  function _getDenom(bytes16 fromType, bytes16 toType, bytes32 host) internal view returns (uint16 denom) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(fromType);
    _keyTuple[1] = bytes32(toType);
    _keyTuple[2] = host;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (uint16(bytes2(_blob)));
  }

  /**
   * @notice Set denom.
   */
  function setDenom(bytes16 fromType, bytes16 toType, bytes32 host, uint16 denom) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(fromType);
    _keyTuple[1] = bytes32(toType);
    _keyTuple[2] = host;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((denom)), _fieldLayout);
  }

  /**
   * @notice Set denom.
   */
  function _setDenom(bytes16 fromType, bytes16 toType, bytes32 host, uint16 denom) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(fromType);
    _keyTuple[1] = bytes32(toType);
    _keyTuple[2] = host;

    StoreCore.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((denom)), _fieldLayout);
  }

  /**
   * @notice Get the full data.
   */
  function get(bytes16 fromType, bytes16 toType, bytes32 host) internal view returns (SwapRatioData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(fromType);
    _keyTuple[1] = bytes32(toType);
    _keyTuple[2] = host;

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreSwitch.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Get the full data.
   */
  function _get(bytes16 fromType, bytes16 toType, bytes32 host) internal view returns (SwapRatioData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(fromType);
    _keyTuple[1] = bytes32(toType);
    _keyTuple[2] = host;

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreCore.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function set(bytes16 fromType, bytes16 toType, bytes32 host, bytes32 hostCopy, uint16 num, uint16 denom) internal {
    bytes memory _staticData = encodeStatic(hostCopy, num, denom);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(fromType);
    _keyTuple[1] = bytes32(toType);
    _keyTuple[2] = host;

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function _set(bytes16 fromType, bytes16 toType, bytes32 host, bytes32 hostCopy, uint16 num, uint16 denom) internal {
    bytes memory _staticData = encodeStatic(hostCopy, num, denom);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(fromType);
    _keyTuple[1] = bytes32(toType);
    _keyTuple[2] = host;

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function set(bytes16 fromType, bytes16 toType, bytes32 host, SwapRatioData memory _table) internal {
    bytes memory _staticData = encodeStatic(_table.hostCopy, _table.num, _table.denom);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(fromType);
    _keyTuple[1] = bytes32(toType);
    _keyTuple[2] = host;

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function _set(bytes16 fromType, bytes16 toType, bytes32 host, SwapRatioData memory _table) internal {
    bytes memory _staticData = encodeStatic(_table.hostCopy, _table.num, _table.denom);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(fromType);
    _keyTuple[1] = bytes32(toType);
    _keyTuple[2] = host;

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Decode the tightly packed blob of static data using this table's field layout.
   */
  function decodeStatic(bytes memory _blob) internal pure returns (bytes32 hostCopy, uint16 num, uint16 denom) {
    hostCopy = (Bytes.getBytes32(_blob, 0));

    num = (uint16(Bytes.getBytes2(_blob, 32)));

    denom = (uint16(Bytes.getBytes2(_blob, 34)));
  }

  /**
   * @notice Decode the tightly packed blobs using this table's field layout.
   * @param _staticData Tightly packed static fields.
   *
   *
   */
  function decode(
    bytes memory _staticData,
    EncodedLengths,
    bytes memory
  ) internal pure returns (SwapRatioData memory _table) {
    (_table.hostCopy, _table.num, _table.denom) = decodeStatic(_staticData);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord(bytes16 fromType, bytes16 toType, bytes32 host) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(fromType);
    _keyTuple[1] = bytes32(toType);
    _keyTuple[2] = host;

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord(bytes16 fromType, bytes16 toType, bytes32 host) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(fromType);
    _keyTuple[1] = bytes32(toType);
    _keyTuple[2] = host;

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(bytes32 hostCopy, uint16 num, uint16 denom) internal pure returns (bytes memory) {
    return abi.encodePacked(hostCopy, num, denom);
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(
    bytes32 hostCopy,
    uint16 num,
    uint16 denom
  ) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory _staticData = encodeStatic(hostCopy, num, denom);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple(bytes16 fromType, bytes16 toType, bytes32 host) internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(fromType);
    _keyTuple[1] = bytes32(toType);
    _keyTuple[2] = host;

    return _keyTuple;
  }
}
