// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { IsPlayer } from "./tables/IsPlayer.sol";
import { Counter } from "./tables/Counter.sol";
import { Approval } from "./tables/Approval.sol";
import { Allowance } from "./tables/Allowance.sol";
import { Balance } from "./tables/Balance.sol";
import { TotalSupply } from "./tables/TotalSupply.sol";
import { StoredSize } from "./tables/StoredSize.sol";
import { Creator } from "./tables/Creator.sol";
import { Commander } from "./tables/Commander.sol";
import { Owner } from "./tables/Owner.sol";
import { EntityType } from "./tables/EntityType.sol";
import { MiningInfo, MiningInfoData } from "./tables/MiningInfo.sol";
import { Path, PathData } from "./tables/Path.sol";
import { Moves } from "./tables/Moves.sol";
import { Terrain } from "./tables/Terrain.sol";
import { TileEntity } from "./tables/TileEntity.sol";
import { Position, PositionData } from "./tables/Position.sol";
import { StatsSpecs } from "./tables/StatsSpecs.sol";
import { HostName } from "./tables/HostName.sol";
import { Equipment } from "./tables/Equipment.sol";
import { RemovedCoord } from "./tables/RemovedCoord.sol";
import { TerrainSpecs, TerrainSpecsData } from "./tables/TerrainSpecs.sol";
import { BuildingSpecs, BuildingSpecsData } from "./tables/BuildingSpecs.sol";
import { SizeSpecs } from "./tables/SizeSpecs.sol";
import { ContainerSpecs } from "./tables/ContainerSpecs.sol";
import { SwapRatio, SwapRatioData } from "./tables/SwapRatio.sol";
import { ConvertRatio, ConvertRatioData } from "./tables/ConvertRatio.sol";
import { MintCosts } from "./tables/MintCosts.sol";
import { UpgradeCosts, UpgradeCostsData } from "./tables/UpgradeCosts.sol";
import { BurnCosts } from "./tables/BurnCosts.sol";
import { BurnAwards } from "./tables/BurnAwards.sol";
import { InteractCosts } from "./tables/InteractCosts.sol";
import { InteractAwards } from "./tables/InteractAwards.sol";
import { StakeSpecs, StakeSpecsData } from "./tables/StakeSpecs.sol";
import { StakingInfo, StakingInfoData } from "./tables/StakingInfo.sol";
import { CookSpecs, CookSpecsData } from "./tables/CookSpecs.sol";
import { CookingInfo, CookingInfoData } from "./tables/CookingInfo.sol";
