// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IBuilding2System
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IBuilding2System {
  function enterBuilding(bytes32 role, uint32 x, uint32 y) external;

  function exitBuilding(bytes32 role, uint32 x, uint32 y, uint32 newX, uint32 newY) external;
}
