// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title ICookSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ICookSystem {
  function cook(bytes32 role, bytes16 outputType, uint32 x, uint32 y) external;

  function serve(bytes32 role, uint32 x, uint32 y) external;
}
