// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IItemSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IItemSystem {
  function craftERC721(bytes16 itemType, bytes32 role) external;

  function consumeERC20(bytes16 itemType, bytes32 role) external;

  function burnERC20(bytes16 itemType, uint128 amount, bytes32 role) external;
}
