// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IPlayerSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IPlayerSystem {
  function spawnHero(string memory name) external returns (uint32, uint32, bytes32);

  function spawnHeroOnCoord(string memory name, bytes32 oldHero, uint32 x, uint32 y) external returns (bytes32);
}
