// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IStakeSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IStakeSystem {
  function stake(bytes32 role, bytes16 outputType, uint32 x, uint32 y) external;

  function unstake(bytes32 role, uint32 x, uint32 y) external;

  function claim(bytes32 role, uint32 x, uint32 y) external;
}
